Reinstate the `merge-queue` label for Mergify
tweag/rules_nixpkgs pull request #199
Opened 2022-03-15 16:49 UTC by aherrmann

It looks like it was lost in [#178](https://github.com/tweag/rules_nixpkgs/pull/178/files#diff-6a30e47dd51449847422017b16878889b848f6602ac56d5a2e67ce8a19afade2L7).
C.f. [rules_haskell's mergify config](https://github.com/tweag/rules_haskell/blob/4c8e6d3b83122ee43949994f4343697d98dbe281/.mergify.yml).

2022-03-16 08:44 UTC, fricklerhandwerk requested changes

2022-03-16 10:59 UTC, aherrmann commented on .mergify.yml
> +          - "merge-queue" name: default
Thanks! Yes, I somehow managed to mess up the copy-paste and not notice.
I've checked it in the [Mergify dashboard](https://dashboard.mergify.com/github/tweag/repo/rules_nixpkgs/config-editor?repositoryName=rules_nixpkgs&pullRequestNumber=199) now.

2022-03-17 11:45 UTC, fricklerhandwerk approved these changes

2022-03-17 11:54 UTC, aherrmann commented
Manual merge, since Mergify config changes cannot be merged by mergify.

2022-03-17 11:54 UTC, merged