Move tests into respective modules
tweag/rules_nixpkgs pull request #213
Opened 2022-03-31 12:43 UTC by fricklerhandwerk

depends on #212
closes #194

2022-04-01 15:28 UTC, avdv requested changes
Overall, LGTM. Just found a nit, and please resolve the conflict in `.github/workflows/workflow.yaml`

BTW, I also tested these changes with the daml project again, just to be safe.

2022-04-01 15:28 UTC, avdv commented on WORKSPACE
> +load("@io_tweag_rules_nixpkgs//nixpkgs:repositories.bzl", "rules_nixpkgs_dependencies")
you load the `rules_nixpkgs_dependencies` twice, first on line 3 and here again.

2022-04-06 07:09 UTC, fricklerhandwerk commented
@avdv Thanks for the hints, fixed.

2022-04-06 08:27 UTC, avdv approved these changes

2022-04-08 10:37 UTC, aherrmann approved these changes
LGTM, Thank you!

2022-04-08 10:38 UTC, merged