`nixpkgs_flake_package()` supplies `--experimental-features 'nix-command flakes'` in case someone's local `nix.conf` hasn't enabled them.
tweag/rules_nixpkgs pull request #465
Opened 2023-12-11 18:14 UTC by rickvanprim

@layus does this seem reasonable?  I'm not aware of any downsides for unconditionally passing these flags.

2023-12-11 21:28 UTC, layus requested changes
I think you need --extra-experimental-features to avoid wiping the features already present in the user config. Otherwise, yes, this is a _very_ good idea :100:

2023-12-11 21:28 UTC, layus commented on core/nixpkgs.bzl
> +    _nixpkgs_build_and_symlink(repository_ctx, [nix_path, "--experimental-features", "nix-command flakes", "build"], expr_args, build_file_content)
```suggestion
    _nixpkgs_build_and_symlink(repository_ctx, [nix_path, "--extra-experimental-features", "nix-command flakes", "build"], expr_args, build_file_content)
```

2023-12-11 21:58 UTC, rickvanprim commented on core/nixpkgs.bzl
> +    _nixpkgs_build_and_symlink(repository_ctx, [nix_path, "--experimental-features", "nix-command flakes", "build"], expr_args, build_file_content)
Good idea!  Done 🙂

2023-12-11 22:00 UTC, rickvanprim commented
One more thought I have while I'm in here, `is_supported_platform()` is currently:
```bazel
def is_supported_platform(repository_ctx):
    return repository_ctx.which("nix-build") != None
```
Should this check to checking `nix` at some point?  And/or should `nixkpkgs_flake_package()` check `nix` and the other rules continue checking `nix-build`?

2023-12-13 14:45 UTC, aherrmann commented
The existence of `nix-build` is just used as a proxy for whether Nix is installed. With modern versions of Nix it could equivalently check for `nix`, I think. But, I don't think we need to conflate these in this PR.

2023-12-13 16:39 UTC, benradf approved these changes

2023-12-14 08:19 UTC, layus approved these changes

2023-12-14 08:20 UTC, merged